name: 'Verify deployed app version'
description: 'make api request to health check endpoint and compare app version in the response'
author: 'Softopus'

inputs:
  url:
    description: 'whole url for the api http get request'
    required: true
  expected:
    description: 'desired app version'
    required: true
  username:
    description: 'username for basic authentication (optional)'
    required: false
  password:
    description: 'password for basic authentication (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Check Live URL
      shell: bash
      run: |
        if [ -n "${{ inputs.username }}" ] && [ -n "${{ inputs.password }}" ]; then
          ${{ github.action_path }}/check.sh "${{ inputs.expected }}" "${{ inputs.url }}" "${{ inputs.username }}" "${{ inputs.password }}"
        else
          ${{ github.action_path }}/check.sh "${{ inputs.expected }}" "${{ inputs.url }}"
        fi
